name: application
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.2 # State Management
  get_storage: ^2.1.1 # Local Storage
  supabase_flutter: ^2.8.4 # Supabase SDK
  google_sign_in: ^6.3.0 # Google Sign In
  fluttertoast: ^8.2.12 # Flutter Toast
  shimmer: ^3.0.0 # Shimmer Effect
  flutter_svg: ^2.0.17 # SVG Images
  permission_handler: ^11.4.0 # Permission Handler
  image_picker: ^1.1.2 # Image Picker
  cached_network_image: ^3.4.1 # Cached Network Image
  internet_connection_checker: ^3.0.1 # Internet Connection Checker
  url_launcher: ^6.3.1 # URL Launcher
  rename_app: ^1.6.2 # Rename App Package
  uuid: ^4.5.1 # UUID Generator
  flutter_holo_date_picker: ^2.0.0 # Date Picker
  flutter_pin_code_fields: ^2.2.0 # Pin Code Fields
  geolocator: ^13.0.4 # Geolocator
  phosphor_flutter: ^2.1.0 # Phosphor Icons
  flutter_rating_bar: ^4.0.1 # Flutter Rating Bar
  date_time_format: ^2.0.1 # Date Time Format
  intl: ^0.20.2
  freezed_annotation: ^2.4.0
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Lints
  build_runner: ^2.3.3
  freezed: ^2.5.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/svg/
    - assets/images/onboarding/
    - assets/bottomNavbar/
    - assets/data/
    - assets/flags/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Rubik-Black.ttf
          weight: 900
